project:
  type: book

book:
  title: "TidyMass tutorial"
  cover-image: figures/tidymass_logo.png
  subtitle: "TidyMass: an object-oriented reproducible analysis framework for LC–MS data"
  abstract: "TidyMass project is a comprehensive computational framework that can process the whole workflow of data processing and analysis for LC-MS-based untargeted metabolomics using tidyverse principles."
  author: "Xiaotao Shen"
  date: "9/4/2022"
  sharing: twitter
  open-graph: true
  twitter-card: 
    site: "@xiaotaoshen1990"
  sidebar:
    search: true
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/tidymass/tidymass_tutorial
        aria-label: GitHub
  chapters:
    - index.qmd
    - install_Rstudio_R.qmd
    - intro.qmd
    - install_tidymass.qmd
    - install_docker.qmd
    - Rstudio_project.qmd
    - massconverter.qmd
    - massprocesser.qmd
    - massdataset.qmd
    - processing_information.qmd
    - operation_of_mass_dataset.qmd
    - add_information.qmd
    - filtering.qmd
    - accessor.qmd
    - merge_split.qmd
    - r_base_function.qmd
    - ggplot2_mass_dataset.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: Litera
  pdf:
    documentclass: scrreprt

editor: visual

website:
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false
